const tags = [
  { name: "Guy", slug: "guy" },
  {
    name: "Happy",
    slug: "happy",
    desc: "Explore our collection of 'Happy LGTM Gifs' to add a burst of joy to your team's GitHub pull request approvals.",
  },
  {
    name: "Laptop",
    slug: "laptop",
    desc: "Dive into our curated 'Laptop LGTM Gifs' to celebrate coding milestones and project completions.",
  },
  { name: "Cute", slug: "cute" },
  {
    name: "Funny",
    slug: "funny",
    desc: "Discover the perfect blend of humor with our 'Funny LGTM Gifs', designed to bring a smile to any developer's face during pull request reviews.",
  },
  {
    name: "Good Job",
    slug: "good-job",
    desc: "Celebrate coding achievements and team victories with our 'Good Job LGTM Gifs', designed to cheer on every successful pull request.",
  },
  {
    name: "Thumbs Up",
    slug: "thumbs-up",
    desc: "Seal your approval with style using our 'Thumbs Up LGTM Gifs', the perfect way to signal a job well done in your code reviews.",
  },
  { name: "Yes", slug: "yes" },
  { name: "90s", slug: "90s" },
  {
    name: "Computer",
    slug: "computer",
    desc: "Enhance your GitHub approvals with our 'Computer LGTM Gifs', showcasing the best tech-themed animations for your project sign-offs.",
  },
  {
    name: "Excited",
    slug: "excited",
    desc: "Bring energy to your pull requests with 'Excited LGTM Gifs', capturing the thrill of nailing that next big code update.",
  },
  {
    name: "Eyes",
    slug: "eyes",
    desc: "Let your peer reviews stand out with 'Eyes LGTM Gifs', perfect for showing meticulous attention to detail in code scrutiny.",
  },
  { name: "Surprised ", slug: "surprised" },
  { name: "Surprise", slug: "surprise" },
  {
    name: "Cat",
    slug: "cat",
    desc: "Add a purr-fect touch to your approvals with our 'Cat LGTM Gifs', because who doesn't love a feline nod to great coding?",
  },
  { name: "Nod", slug: "nod" },
  {
    name: "Smile",
    slug: "smile",
    desc: "Spread positivity in your team's GitHub workflow with 'Smile LGTM Gifs', the best way to add a friendly face to code approvals.",
  },
  {
    name: "Keyboard",
    slug: "keyboard",
    desc: "Acknowledge typing prowess and coding mastery with 'Keyboard LGTM Gifs', celebrating every keystroke of genius.",
  },
  {
    name: "Dog",
    slug: "dog",
    desc: "Woof your way to cheerful approvals with 'Dog LGTM Gifs', bringing a dose of adorable to your code review process.",
  },
  { name: "Female", slug: "female" },
  { name: "Point", slug: "point" },
  {
    name: "Dance",
    slug: "dance",
    desc: "Liven up your project sign-offs with 'Dance LGTM Gifs', because every merged pull request deserves a happy dance.",
  },
  { name: "Impressed", slug: "impressed" },
  {
    name: "Clap",
    slug: "clap",
    desc: "Applaud your team's hard work with 'Clap LGTM Gifs', making every code approval an occasion for celebration.",
  },
  { name: "Tim and Eric", slug: "tim-and-eric" },
  { name: "Awkward", slug: "awkward" },
  {
    name: "Nice",
    slug: "nice",
    desc: "Commend stellar coding with 'Nice LGTM Gifs', the perfect reaction to spot-on solutions and slick implementations.",
  },
  { name: "Glasses", slug: "glasses" },
  { name: "Retro", slug: "retro", desc: "" },
  { name: "Boy", slug: "boy" },
  {
    name: "Seinfeld",
    slug: "seinfeld",
    desc: "Inject classic humor into your approvals with 'Seinfeld LGTM Gifs', channeling the iconic sitcom's vibe into your project reviews.",
  },
  {
    name: "Desktop",
    slug: "desktop",
    desc: "Showcase your desktop devotion with 'Desktop LGTM Gifs', highlighting the heart of hardware enthusiasm in every approval.",
  },
  { name: "Captain", slug: "captain" },
  { name: "The Office", slug: "the-office" },
  { name: "Weird", slug: "weird" },
  { name: "Tom Hanks", slug: "tom-hanks" },
  { name: "Ready", slug: "ready" },
  { name: "Beyonce", slug: "beyonce" },
  { name: "Pretty", slug: "pretty" },
  { name: "NBA", slug: "nba" },
  { name: "Woman", slug: "woman" },
  { name: "Perfect", slug: "perfect" },
  { name: "Friends", slug: "friends" },
  { name: "Derpy", slug: "derpy" },
  { name: "Joker", slug: "joker" },
  { name: "Star Wars", slug: "star-wars" },
  { name: "Kid", slug: "kid" },
  { name: "Kanye", slug: "kanye" },
];

export default tags;
