const tags = [
  { name: "Guy", slug: "guy" },
  { name: "Happy", slug: "happy" },
  { name: "Laptop", slug: "laptop" },
  { name: "Cute", slug: "cute" },
  { name: "Funny", slug: "funny" },
  { name: "Good Job", slug: "good-job" },
  { name: "Thumbs Up", slug: "thumbs-up" },
  { name: "Yes", slug: "yes" },
  { name: "90s", slug: "90s" },
  { name: "Computer", slug: "computer" },
  { name: "Excited", slug: "excited" },
  { name: "Eyes", slug: "eyes" },
  { name: "Surprised ", slug: "surprised" },
  { name: "Surprise", slug: "surprise" },
  { name: "Cat", slug: "cat" },
  { name: "Nod", slug: "nod" },
  { name: "Smile", slug: "smile" },
  { name: "Keyboard", slug: "keyboard" },
  { name: "Dog", slug: "dog" },
  { name: "Female", slug: "female" },
  { name: "Point", slug: "point" },
  { name: "Dance", slug: "dance" },
  { name: "Impressed", slug: "impressed" },
  { name: "Clap", slug: "clap" },
  { name: "Tim and Eric", slug: "tim-and-eric" },
  { name: "Awkward", slug: "awkward" },
  { name: "Nice", slug: "nice" },
  { name: "Glasses", slug: "glasses" },
  { name: "Retro", slug: "retro" },
  { name: "Boy", slug: "boy" },
  { name: "Seinfeld", slug: "seinfeld" },
  { name: "Desktop", slug: "desktop" },
  { name: "Captain", slug: "captain" },
  { name: "The Office", slug: "the-office" },
  { name: "Weird", slug: "weird" },
  { name: "Tom Hanks", slug: "tom-hanks" },
  { name: "Ready", slug: "ready" },
  { name: "Beyonce", slug: "beyonce" },
  { name: "Pretty", slug: "pretty" },
  { name: "NBA", slug: "nba" },
  { name: "Woman", slug: "woman" },
  { name: "Perfect", slug: "perfect" },
  { name: "Friends", slug: "friends" },
  { name: "Derpy", slug: "derpy" },
  { name: "Joker", slug: "joker" },
  { name: "Star Wars", slug: "star-wars" },
  { name: "Kid", slug: "kid" },
  { name: "Kanye", slug: "kanye" },
];

export default tags;
